### ISSUE TITLE
Help putting screens together by importing in kivy

### ISSUE THREAD

**Issue by ttsuchi** [ttsuchi/neural-network-demo#9]
Jahaziel asked me:

> Hi Tomoki,
> 
> It's Jahaziel from ERSP. I was wondering if you could help me understand how to put screens together in kivy by importing? I've been looking on google but can't find any good tutorials or places where I can see how to do this. Any help is appreciated. Thanks!

**Comment by ttsuchi** [comment]
Hi @jahaziel1313 , please see my commit 14fa9b1 for an example of how to split code for different screens into different files.  As you can see, you can
- Put the main "controller" logic in a single file, in this case `main.py`.
- Put each screen (or however you want to split code) into different files, for example `pca.py` and `dataset.py`.
- From `main.py`, you can reference _anything_ (functions, classes, variables) in some other file by using the `import` statement.  For instance, to use `RunPCA` class from `pca.py`, simply include

`from pca import RunPCA`

(There are several variants to this syntax.  For example, you can also do `from pca import *` to import everything from `pca.py`.)

Hope this helps!

**Comment by jahaziel1313** [comment]
This helped so much! I solved the issue now. Thanks a lot, Tomoki!
